#!/bin/bash
fswebcam -d v4l2:/dev/video0 -i 0 -c /home/pi/picturecollector/src/c525config.txt /home/pi/picturecollector/webcam/${1}.png

#fswebcam --png 9 -d v4l2:/dev/video0 -i 0 --set Focus, Auto=False --no-banner --greyscale --no-shadow --no-title --no-subtitle --no-timestamp --no-info --no-underlay --no-overlay -r 1281x720 /home/pi/picturecollector/webcam/${1}.png
